### ISSUE TITLE
Karma icon on user profiles is not clear enough

### ISSUE THREAD

**Issue by Discordius** [ForumMagnum/ForumMagnum#261]
![Karma Icon](https://imgur.com/a/ycofa)

The star that we use as a symbol for Karma is not clear enough, and the tooltip doesn't really show up fast enough. We might want to replace that with text, or maybe choose an icon that more naturally communicates the meaning.

┆Issue is synchronized with this [Trello card](https://trello.com/c/Hg4Dv0w0) by [Unito](https://www.unito.io/learn-more)

**Comment by jimrandomh** [comment]
The image in this issue is broken; I presume you mean the star icon? Currently it doesn't have any tooltip; that was accidentally dropped in [this commit](https://github.com/LessWrong2/Lesswrong2/commit/7bc62db0036801ad7514af0c88fb56d6a5401bb7#diff-dfa0b2833d9399b5bf4f769238ce9b63). We probably want a tooltip that uses an actual Tooltip component, and appears without a delay, rather than an alt-text-style delayed hover.

**Comment by tdnzr** [comment]
The karma icon on the user page now has an instant tooltip, so this issue can likely be closed.
