### ISSUE TITLE
Feature Request - subscription to sequences

### ISSUE THREAD

**Issue by edoarad** [ForumMagnum/ForumMagnum#6936]
A user asks to be notified of new posts in a sequence: https://forum.effectivealtruism.org/posts/ZcogAdNfGGuw88vKu/forecasting-the-cost-effectiveness-of-trying-something-new?commentId=RssgcRLzCtSCeXs68

I think there should be 

1. A "subscribe" button in a sequence (similar to subscribing to a user)
1. An option to subscribe to new posts in a sequence from each post in it (say, next to the other subscribe options)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/628521446211730/1204363541867832) by [Unito](https://www.unito.io)

**Comment by jpaddison3** [comment]
[Another request](https://forum.effectivealtruism.org/posts/NhSBgYq55BFs7t2cA/ea-forum-feature-suggestion-thread?commentId=YmEqJxEgckgyZpi6C).

**Comment by s-cheng** [comment]
1 is done in https://github.com/ForumMagnum/ForumMagnum/pull/9039

2 is a bit more complicated because posts can be in multiple sequences, so I feel it will take more thought to implement. I'm going to close this issue for now since the basic functionality is there, and we can revisit if this comes up again.
